CREATE TABLE BARUN (
	SEQNO				INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	WORK_DAY 		VARCHAR(20) NOT NULL,
	START_TIME 		VARCHAR(30) NOT NULL,
	END_TIME 		VARCHAR(30) NOT NULL,
	WORK_CONTENT	TEXT			NOT NULL

) ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;



