CREATE TABLE TB_USER (
	USER_ID VARCHAR(30) NOT NULL,
	PASSWD VARCHAR(512) NOT NULL,
	USER_NAME VARCHAR(20) NOT NULL,
	BRAND_NAME VARCHAR(30),
	PHONE VARCHAR(512) NOT NULL,
	DRIVER_NUM INT DEFAULT 0,
	ROLE  ENUM('ADMIN','DRIVER','WAREHOUSE'),
	PRIMARY KEY (USER_ID)
) ENGINE=InnoDB DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;


INSERT INTO TB_USER(USER_ID,PASSWD,USER_NAME,PHONE,ROLE) VALUES('root',password('ghkdeotns'),'황대순',password('010-6822-0010'),'ADMIN');

INSERT INTO TB_USER(USER_ID,PASSWD,USER_NAME,PHONE,DRIVER_NUM,ROLE) VALUES('driver1',sha2('driver1',512),'1번기사',sha2('010-1111-2222',512),1,'DRIVER');
